from fastapi import APIRouter, HTTPException
from typing import List, Dict, Optional, Any
from datetime import datetime, timedelta
import logging

logger = logging.getLogger(__name__)

router = APIRouter()

@router.get("/signals/recent")
async def get_recent_signals():
    """Get recent signals generated by all strategies - Required for zero trades diagnosis"""
    try:
        # Get recent signals from orchestrator
        from src.core.orchestrator import get_orchestrator_instance
        
        orchestrator = get_orchestrator_instance()
        recent_signals = []
        
        if orchestrator and hasattr(orchestrator, 'strategies'):
            # Get recent signals from all strategies
            for name, strategy in orchestrator.strategies.items():
                try:
                    # Check if strategy has recent signals
                    if hasattr(strategy, 'recent_signals'):
                        strategy_signals = getattr(strategy, 'recent_signals', [])
                        for signal in strategy_signals:
                            signal_data = {
                                'strategy': name,
                                'signal': signal,
                                'timestamp': datetime.now().isoformat(),
                                'source': 'orchestrator'
                            }
                            recent_signals.append(signal_data)
                    
                    # Check if strategy has signal history
                    if hasattr(strategy, 'signal_history'):
                        signal_history = getattr(strategy, 'signal_history', [])
                        for signal in signal_history[-5:]:  # Last 5 signals
                            signal_data = {
                                'strategy': name,
                                'signal': signal,
                                'timestamp': datetime.now().isoformat(),
                                'source': 'strategy_history'
                            }
                            recent_signals.append(signal_data)
                            
                except Exception as e:
                    logger.error(f"Error getting signals from strategy {name}: {e}")
                    continue
        
        # ELIMINATED: Test signal generation removed - no fake signals allowed
        # Original violation: Generated fake NIFTY/BANKNIFTY signals with hardcoded prices
        # This could trigger real trading decisions with fake data
        
        # If no real signals found, return empty result - no fake fallbacks
        if not recent_signals:
            logger.warning("No recent signals found - returning empty result (no fake signals)")
            recent_signals = []
        
        return {
            "success": True,
            "signals": recent_signals,
            "signal_count": len(recent_signals),
            "timestamp": datetime.now().isoformat(),
            "message": f"Found {len(recent_signals)} recent signals"
        }
        
    except Exception as e:
        logger.error(f"Error getting recent signals: {str(e)}")
        return {
            "success": False,
            "signals": [],
            "signal_count": 0,
            "error": str(e),
            "timestamp": datetime.now().isoformat(),
            "message": "Failed to get recent signals"
        }

@router.get("/signals/strategy/{strategy_name}")
async def get_signals_by_strategy(strategy_name: str):
    """Get signals from a specific strategy"""
    try:
        from src.core.orchestrator import get_orchestrator_instance
        
        orchestrator = get_orchestrator_instance()
        
        if orchestrator and hasattr(orchestrator, 'strategies'):
            strategy = orchestrator.strategies.get(strategy_name)
            
            if strategy:
                signals = []
                
                # Get signals from strategy
                if hasattr(strategy, 'recent_signals'):
                    signals.extend(getattr(strategy, 'recent_signals', []))
                
                if hasattr(strategy, 'signal_history'):
                    signals.extend(getattr(strategy, 'signal_history', []))
                
                return {
                    "success": True,
                    "strategy": strategy_name,
                    "signals": signals,
                    "signal_count": len(signals),
                    "timestamp": datetime.now().isoformat()
                }
            else:
                return {
                    "success": False,
                    "strategy": strategy_name,
                    "signals": [],
                    "signal_count": 0,
                    "error": "Strategy not found",
                    "timestamp": datetime.now().isoformat()
                }
        else:
            return {
                "success": False,
                "strategy": strategy_name,
                "signals": [],
                "signal_count": 0,
                "error": "Orchestrator not available",
                "timestamp": datetime.now().isoformat()
            }
            
    except Exception as e:
        logger.error(f"Error getting signals for strategy {strategy_name}: {str(e)}")
        return {
            "success": False,
            "strategy": strategy_name,
            "signals": [],
            "signal_count": 0,
            "error": str(e),
            "timestamp": datetime.now().isoformat()
        } 